<?php
$product = $block->getProduct();
?>
<div class="hook-reviews">
	<a class="customize-box" href="<?php echo $product->getProductUrl(); ?>">
		<span class="customize-label" style="font-size: 11px; line-height: 11px; letter-spacing: 1px;"><?php echo __('Customize'); ?></span>
	</a>
</div>
<script>
require([
'jquery', // jquery Library
'jquery/ui', // Jquery UI Library
'mage/translate' // Magento text translate (Validation message translte as per language)
], function($){ 
    $(document).ready(function() {
        $('.product-items .product-item').each(function(){
            if($(this).find('.customize-box').length > 0){
                $(this).find('.tocart').css('display', 'none');
                $(this).find('.actions-primary').css('display', 'none');
            }
            
        })
    });
});
</script>