<?php
//labels
$element_label = __('Element Title');
$position_label = __('Position');
$scale_label = __('Scale');
$dimensions_label = __('Dimensions');
$angle_label = __('Angle');
$colors_label = __('Color(s)');

?>

<div class="fpd-editor-box">
	<p><span><?php echo $element_label; ?>: </span><i class="fpd-current-element"></i></p>
	<p><span><?php echo $position_label; ?>: </span><i class="fpd-position"></i></p>
	<p><span><?php echo $scale_label; ?>: </span><i class="fpd-scale"></i></p>
	<p><span><?php echo $dimensions_label; ?>: </span><i class="fpd-dimensions"></i></p>
	<p><span><?php echo $angle_label; ?>: </span><i class="fpd-degree"></i></p>
	<p><span><?php echo $colors_label; ?>: </span><i class="fpd-color"></i></p>
</div>