<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$currency_helper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php $customizeData = $block->getCustomizedcartdata(); ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if(count($customizeData)) { ?>
	<style>
	.customizationUploaded {float:left; padding-bottom:5px; width:100%;}
	.customization-ul {margin:0px; padding:0px;}
	.customization-li {list-style: none;}
	.customization-img {float:left;}
	.customization-price{float:right;}
	.customization-anc {display:block;}
	</style>
	<?php $i =1; ?>
	<?php foreach($customizeData as $cData) { ?>
		<tr>
			<td style="BORDER-TOP: none;">
				<div class="customizationUploaded">
					<ul class="customization-ul">
						<li class="customization-li">
							<?php if($cData['image_name'] != '') { ?>
								<div class="customization-img"><p><b><?php echo __('Picture '); ?>#<?php echo $i; ?></b></p><a target="_blank" href="<?php echo $block->getcimageUrl($cData['image_name']); ?>"><img src="<?php echo $block->getcimageUrl($cData['image_name']); ?>" alt="<?php echo __('Download Image'); ?>"></a></div>
								<?php $i++; ?>
							<?php } ?>
						</li>
					</ul>
				</div>
			</td>
			<td style="BORDER-TOP: none;">&nbsp;</td>
			<td style="BORDER-TOP: none;">
				<div class="customization-price">
					<?php echo $currency_helper->currency($cData['new_price'], true, false); ?>
				</div>
			</td>
		</tr>
	<?php } ?>
<?php } ?>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
